### ISSUE TITLE
Use named parameters in query language templates

### ISSUE THREAD

**Issue by batpad** [mapbox/overpass-queries#1]
Having many `%s` in the templates is going to get confusing as it is going to depend on the order of those parameters and prone to error if we move parameters around / have different parameters.

Let's use named parameters in the templates so that we are not dependent on the order of the parameters.

So do something like `%(timeStart)s` instead of `%s` - we can then use something like [sprintf-js](https://www.npmjs.com/package/sprintf-js) when we need to perform the substitution.

cc @ramyaragupathy

**Comment by ramyaragupathy** [comment]
https://github.com/mapbox/overpass-queries/commit/34a98ac499abaad59faaef748ddbd47cf0a966e1
